const jwt = require('jsonwebtoken')

const value = {
    name: "Ayush",
    accountNumber: 123456
}

const token = jwt.sign(value, "secret")

// this token is generated by the secret hence it can only be verified by the token
console.log(token)

const verifiedValue = jwt.verify("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQXl1c2giLCJhY2NvdW50TnVtYmVyIjoxMjM0NTYsImlhdCI6MTczNzM3Mzk4OX0.hefOso9IMu2PSJsyp8393lSxOgzltCw21EYWOcihRk8", "secret")

console.log(verifiedValue)